#!/usr/bin/env python3
"""Compile the base's accumulated warnings into one retrievable index.

Every concept carries four kinds of negative knowledge, and until now they were
only reachable by opening the concept that happened to hold them:

    misconceptions          - what people wrongly believe
    exceptions              - where the concept does not apply
    false_positive_traps    - where a detector would wrongly fire
    terminology.avoid       - phrasings an explanation must not use

That is exactly backwards for the way they get used. An explanation layer needs
to ask "is there anything I must not say about this position?" without knowing
in advance which concept holds the warning, and a reviewer needs to see every
unhedged claim in one place. So this builds the inverted index.

The output is generated, never hand-edited: rebuild it rather than patch it.

    python3 tools/build_index.py            # write state/warnings_index.json
    python3 tools/build_index.py --check    # non-zero if the file is stale
"""
import json, glob, os, sys, datetime, hashlib

OUT = "state/warnings_index.json"


def build():
    entries, by_kind = [], {}
    concepts = 0
    for f in sorted(glob.glob("concepts/*/*.json")):
        c = json.load(open(f))
        concepts += 1
        base = {"concept": c["id"], "category": c.get("category"),
                "knowledge_type": c.get("knowledge_type"),
                "difficulty": c.get("difficulty"), "path": f}
        for kind, items in (
                ("misconception", c.get("misconceptions", [])),
                ("exception", c.get("exceptions", [])),
                ("false_positive_trap", c.get("recognition", {}).get("false_positive_traps", [])),
                ("avoid_phrasing", c.get("terminology", {}).get("avoid", []))):
            for text in items:
                entries.append(dict(base, kind=kind, text=text))
                by_kind[kind] = by_kind.get(kind, 0) + 1

    # Concepts whose type demands a hedge are worth surfacing separately: a
    # rule-of-thumb with no recorded exception is a claim overstating itself.
    unhedged = []
    for f in sorted(glob.glob("concepts/*/*.json")):
        c = json.load(open(f))
        soft = c.get("knowledge_type") in (
            "rule-of-thumb", "strategic-principle", "practical-guideline",
            "historical-teaching-principle", "positional-concept")
        if soft and not c.get("exceptions"):
            unhedged.append(c["id"])

    return {
        "version": 1,
        "note": ("GENERATED by tools/build_index.py - do not edit by hand. An inverted index of "
                 "every warning the concept base carries, so an explanation layer can ask what it "
                 "must not say without knowing which concept holds the answer."),
        "generated": datetime.date.today().isoformat(),
        "concepts_indexed": concepts,
        "counts": dict(sorted(by_kind.items())),
        "total": len(entries),
        "soft_concepts_without_exceptions": unhedged,
        "entries": entries,
    }


def main():
    os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
    fresh = build()
    if "--check" in sys.argv:
        if not os.path.exists(OUT):
            print("warnings index missing; run tools/build_index.py"); return 1
        old = json.load(open(OUT))
        # `generated` is a date, so compare everything else.
        a = {k: v for k, v in old.items() if k != "generated"}
        b = {k: v for k, v in fresh.items() if k != "generated"}
        if a != b:
            print("warnings index is STALE; run tools/build_index.py"); return 1
        print(f"warnings index current: {old['total']} entries")
        return 0
    json.dump(fresh, open(OUT, "w"), indent=2, ensure_ascii=False)
    print(f"wrote {OUT}: {fresh['total']} warnings from {fresh['concepts_indexed']} concepts")
    print("  " + " ".join(f"{k}={v}" for k, v in fresh["counts"].items()))
    if fresh["soft_concepts_without_exceptions"]:
        print(f"  soft-typed concepts with NO exception recorded: "
              f"{len(fresh['soft_concepts_without_exceptions'])} -> "
              f"{', '.join(fresh['soft_concepts_without_exceptions'])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
